version: '3.3'
services:
  mysql:
    container_name: mysql-development
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    networks:
      - network-development
    volumes:
      - volume-development:/var/lib/mysql
  adminer:
    container_name: adminer-development
    image: adminer
    ports:
      - "8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - network-development
networks:
  network-development:
volumes:
  volume-development: